### ISSUE TITLE
Incompatibility with other mods

### ISSUE THREAD

**Issue by Steveplays28** [polina4096/butter#1]
Crash on startup due to a mixin failure.
https://mclo.gs/vvchqwd

**Comment by Steveplays28** [comment]
Alright, I'll do some testing when I have time.
Could also be bedrockify or smooth swapping, just some shouts though.

**Comment by Rozbiynk** [comment]
seems like bedrockify

**Comment by Steveplays28** [comment]
Thank you for the fix.
